input {
  file {
    path => [
      "C:/elastic/data/Training/02.label/TL_1.suncheon/*.csv",
      "C:/elastic/data/Training/02.label/TL_2.mokpo/*.csv",
      "C:/elastic/data/Training/02.label/TL_3.yeosu/*.csv",
      "C:/elastic/data/Training/02.label/TL_4.gwangyang/*.csv",
      "C:/elastic/data/Training/02.label/TL_5.naju/*.csv",
      "C:/elastic/data/Training/02.label/TL_6.industry/*.csv"
    ]
    start_position => "beginning"
    sincedb_path => "NUL"
    add_field => {"dataset" => "training"}
  }
}

filter {
  csv {
    skip_header => true
    separator => ","
    columns => ["memberID", "QUST_ID", "QITM_CN", "QITM_EN", "RSPNS_CN"]

  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "power-label-v1"
  }
}     