input {
  file {
    path => [
      "C:/elastic/data/Validation/01.source/VS_1.suncheon/*.csv",
      "C:/elastic/data/Validation/01.source/VS_2.mokpo/*.csv",
      "C:/elastic/data/Validation/01.source/VS_3.yeosu/*.csv",
      "C:/elastic/data/Validation/01.source/VS_4.gwangyang/*.csv",
      "C:/elastic/data/Validation/01.source/VS_5.naju/*.csv",
      "C:/elastic/data/Validation/01.source/VS_6.industry/*.csv",
      "C:/elastic/data/Validation/01.source/VS_weatherdata/*.csv"
    ]
    start_position => "beginning"
    sincedb_path => "NUL"
    add_field => {"dataset" => "validation"}
  }
}

filter {
  csv {
    skip_header => true
    separator => ","
    columns => ["memberID", "mrdDt", "pwrQrt"]
  }

  mutate {
    convert => {
      "pwrQrt" => "float"
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "power-usage-validation-v2"
  }
}