input {
  file {
    path => [
      "C:/elastic/data/Validation/02.label/VL_1.suncheon/*.csv",
      "C:/elastic/data/Validation/02.label/VL_2.mokpo/*.csv",
      "C:/elastic/data/Validation/02.label/VL_3.yeosu/*.csv",
      "C:/elastic/data/Validation/02.label/VL_4.gwangyang/*.csv",
      "C:/elastic/data/Validation/02.label/VL_5.naju/*.csv",
      "C:/elastic/data/Validation/02.label/VL_6.industry/*.csv"
    ]
    start_position => "beginning"
    sincedb_path => "NUL"
    mode => "read"
    exit_after_read => true
    add_field => {"dataset" => "validation"}
  }
}

filter {
  csv {
    skip_header => true
    separator => ","
    columns => ["memberID", "QUST_ID", "QITM_CN", "QITM_EN", "RSPNS_CN"]
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "power-label-validation-v1"
  }
}     