input {
  file {
    path => [
      "C:/elastic/data/Training/01.source/TS_1.suncheon/*.csv",
      "C:/elastic/data/Training/01.source/TS_2.mokpo/*.csv",
      "C:/elastic/data/Training/01.source/TS_3.yeosu/*.csv",
      "C:/elastic/data/Training/01.source/TS_4.gwangyang/*.csv",
      "C:/elastic/data/Training/01.source/TS_5.naju/*.csv",
      "C:/elastic/data/Training/01.source/TS_6.industry/*.csv",
      "C:/elastic/data/Training/01.source/TS_weatherdata/*.csv"
    ]
    start_position => "beginning"
    sincedb_path => "NUL"
    add_field => {"dataset" => "training"}
  }
}

filter {
  csv {
    separator => ","
    columns => ["memberID", "mrdDt", "pwrQrt"]
  }

  mutate {
    convert => {
      "pwrQrt" => "float"
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "power-usage-v2"
  }
}